DOCKER_GBSYNCD_PLATFORM_CODE = credo

LIBSAI_VERSION = 1.2.12
LIBSAI_CREDO = libsaicredo_$(LIBSAI_VERSION)_amd64.deb
$(LIBSAI_CREDO)_URL = "$(BUILD_PUBLIC_URL)/credosai/$(LIBSAI_CREDO)"
LIBSAI_CREDO_OWL = libsaicredo-owl_$(LIBSAI_VERSION)_amd64.deb
$(LIBSAI_CREDO_OWL)_URL = "$(BUILD_PUBLIC_URL)/credosai/$(LIBSAI_CREDO_OWL)"
LIBSAI_CREDO_BLACKHAWK = libsaicredo-blackhawk_$(LIBSAI_VERSION)_amd64.deb
$(LIBSAI_CREDO_BLACKHAWK)_URL = "$(BUILD_PUBLIC_URL)/credosai/$(LIBSAI_CREDO_BLACKHAWK)"
LIBSAI_CREDO_CRT88322 = libsaicredo-crt88322_$(LIBSAI_VERSION)_amd64.deb
$(LIBSAI_CREDO_CRT88322)_URL = "$(BUILD_PUBLIC_URL)/credosai/$(LIBSAI_CREDO_CRT88322)"

ifneq ($($(LIBSAI_CREDO)_URL),)
include $(PLATFORM_PATH)/../template/docker-gbsyncd-trixie.mk
$(DOCKER_GBSYNCD_BASE)_VERSION = 1.0.0
$(DOCKER_GBSYNCD_BASE)_PACKAGE_NAME = gbsyncd
$(DOCKER_GBSYNCD_BASE)_PATH = $(PLATFORM_PATH)/../components/docker-gbsyncd-$(DOCKER_GBSYNCD_PLATFORM_CODE)
SONIC_ONLINE_DEBS += $(LIBSAI_CREDO) $(LIBSAI_CREDO_OWL) $(LIBSAI_CREDO_BLACKHAWK) $(LIBSAI_CREDO_CRT88322)
$(DOCKER_GBSYNCD_BASE)_DEPENDS += $(SYNCD) $(LIBSAI_CREDO) $(LIBSAI_CREDO_OWL) $(LIBSAI_CREDO_BLACKHAWK) $(LIBSAI_CREDO_CRT88322)
endif
