#!/bin/bash

readonly SHOW_COMMAND_PATTERN='^show($| [a-zA-Z0-9%()*+,./:<=>?@^_~ -]+$)'
readonly VTYSH=/usr/bin/vtysh

reject_command()
{
    echo "Not allowed to run command. Please run sudo vtysh instead." >&2
    exit 1
}

namespace=
namespace_set=0
commands=()

while (( $# > 0 )); do
    case "$1" in
        -n)
            (( $# >= 2 && namespace_set == 0 )) || reject_command
            [[ "$2" =~ ^[0-9]+$ ]] || reject_command
            namespace="$2"
            namespace_set=1
            shift 2
            ;;
        -c)
            (( $# >= 2 )) || reject_command
            [[ "$2" =~ $SHOW_COMMAND_PATTERN ]] || reject_command
            commands+=("$2")
            shift 2
            ;;
        *)
            reject_command
            ;;
    esac
done

(( ${#commands[@]} > 0 )) || reject_command

arguments=()
if (( namespace_set == 1 )); then
    arguments+=("-n" "$namespace")
fi

for command in "${commands[@]}"; do
    arguments+=("-c" "$command")
done

unset VTYSH_PAGER PAGER
exec "$VTYSH" "${arguments[@]}"
