# libsensors configuration file

bus "i2c-0"  "I2C Synopsys DesignWare I2C adapter"
bus "i2c-8"  "i2c-0-mux (chan_id 2)"
bus "i2c-9"  "i2c-0-mux (chan_id 3)"
bus "i2c-76" "i2c-70-mux (chan_id 6)"

chip "k10temp-pci-00c3"
    label temp1 "CPU"

chip "lm75-i2c-*-4a"
    label temp1 "PSU-A Intake"
    set temp1_max 64
    set temp1_max_hyst 59

chip "lm75-i2c-*-4b"
    label temp1 "PSU-B Intake"
    set temp1_max 64
    set temp1_max_hyst 59

chip "lm75-i2c-*-4c"
    label temp1 "MAC Heatsink"
    set temp1_max 85
    set temp1_max_hyst 80

chip "lm75-i2c-*-4d"
    label temp1 "Ambient"
    set temp1_max 61
    set temp1_max_hyst 56

chip "lm75-i2c-*-4e"
    label temp1 "Fan Board"
    set temp1_max 61
    set temp1_max_hyst 56

chip "ucd9090-i2c-*-41"
    label temp1 "UCD9090"
    label in1 "12V"
    label in2 "5.0V"
    label in3 "3.3V_1"
    label in4 "3.3V_2"
    label in5 "1.8V"
    label in6 "1.1V"
    label in7 "0.865V"
    label in8 "0.8V"
    label in9 "0.9V"
    set in9_crit 1.035
    set in9_lcrit 0.765
    set in9_min 0.810
    set in9_max 0.990
    set temp1_max 75
    set temp1_crit 80

chip "fan_cpld-i2c-9-5f"
    label fan1 "Fan_1 speed"
    compute fan1 @*120, @/120
    label fan2 "Fan_2 speed"
    compute fan2 @*120, @/120
    label fan3 "Fan_3 speed"
    compute fan3 @*120, @/120
    label fan4 "Fan_4 speed"
    compute fan4 @*120, @/120
    label fan5 "Fan_5 speed"
    compute fan5 @*120, @/120
    label fan6 "Fan_6 speed"
    compute fan6 @*120, @/120
    label fan7 "Fan_7 speed"
    compute fan7 @*120, @/120
    label fan8 "Fan_8 speed"
    compute fan8 @*120, @/120
    label fan9 "Fan_9 speed"
    compute fan9 @*120, @/120
    label fan10 "Fan_10 speed"
    compute fan10 @*120, @/120
