# libsensors configuration file

bus "i2c-0"  "I2C I801"
bus "i2c-1"  "I2C iSMT"
bus "i2c-4"  "i2c-0-mux (chan_id 2)"
bus "i2c-5"  "i2c-0-mux (chan_id 3)"
bus "i2c-72" "i2c-1-mux (chan_id 6)"

chip "jc42-i2c-*-18"
    label temp1 "DIMM"
    set temp1_max 85
    set temp1_crit 95
    set temp1_crit_hyst 90

chip "lm75-i2c-*-4f"
    label temp1 "CPU"
    set temp1_max 80
    set temp1_max_hyst 75

chip "lm75-i2c-*-4a"
    label temp1 "PSU-A Intake"
    set temp1_max 64
    set temp1_max_hyst 59

chip "lm75-i2c-*-4b"
    label temp1 "PSU-B Intake"
    set temp1_max 64
    set temp1_max_hyst 59

chip "lm75-i2c-*-4c"
    label temp1 "MAC Heatsink"
    set temp1_max 85
    set temp1_max_hyst 80

chip "lm75-i2c-*-4d"
    label temp1 "Ambient"
    set temp1_max 61
    set temp1_max_hyst 56

chip "lm75-i2c-*-4e"
    label temp1 "Fan Board"
    set temp1_max 61
    set temp1_max_hyst 56

chip "ucd9090-i2c-*-41"
    label temp1 "UCD9090"
    label in1 "12V"
    compute in1 @/(1000), @*1000
    label in2 "5V"
    compute in2 @/(1000), @*1000
    label in3 "3.3V"
    compute in3 @/(1000), @*1000
    label in4 "2.5V"
    compute in4 @/(1000), @*1000
    label in5 "1.8V"
    compute in5 @/(1000), @*1000
    ignore in6
    ignore in7
    ignore in8
    set in9_crit 0.990
    set in9_lcrit 0.810
    set in9_min 0.830
    set in9_max 0.970
    set temp1_max 75
    set temp1_crit 80


chip "fan_cpld-i2c-5-5f"
    label fan1 "Fan_1 speed"
    compute fan1 300000/@, @/300000
    label fan2 "Fan_2 speed"
    compute fan2 300000/@, @/300000
    label fan3 "Fan_3 speed"
    compute fan3 300000/@, @/300000
    label fan4 "Fan_4 speed"
    compute fan4 300000/@, @/300000
    label fan5 "Fan_5 speed"
    compute fan5 300000/@, @/300000
    label fan6 "Fan_6 speed"
    compute fan6 300000/@, @/300000
    label fan7 "Fan_7 speed"
    compute fan7 300000/@, @/300000
    label fan8 "Fan_8 speed"
    compute fan8 300000/@, @/300000
    label fan9 "Fan_9 speed"
    compute fan9 300000/@, @/300000
    label fan10 "Fan_10 speed"
    compute fan10 300000/@, @/300000
    label fan11 "Fan_11 speed"
    compute fan11 300000/@, @/300000
    label fan12 "Fan_12 speed"
    compute fan12 300000/@, @/300000
