#!/usr/bin/env python3

# Copyright 2026 Nexthop Systems Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import os
import os.path

from nexthop import voltage_cli


if __name__ == "__main__":
    voltage_cli.cli()
